[package]
name = "sudoku"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fast-math = "0.1.1"
itertools = "0.12.0"
libm = "0.2.8"
rand = "0.8.5"
