name: Rust

on:
  push:
    branches: [ "sa-grids", "main" ]
  pull_request:
    branches: [ "sa-grids", "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set Path variable for Templates
      run: echo "TEMPLATE_DIR=${{github.workspace}}/static" >> $GITHUB_ENV
    - name: Verify Template Path
      run: echo "Template path -> $TEMPLATE_DIR"
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Clippy
      run: cargo clippy --verbose -- -D warnings
